import type {
    AppUser,
    Category,
    Product,
    StockIn,
    Supplier,
    Transaction,
} from "./types";

export const categories: Category[] = [
    { id: 1, name: "Minuman", description: "Air mineral, teh, kopi, soft drink" },
    { id: 2, name: "Makanan Ringan", description: "Snack, biskuit, keripik" },
    { id: 3, name: "Rokok", description: "Aneka rokok kretek dan filter" },
    { id: 4, name: "Sembako", description: "Beras, gula, minyak, tepung" },
    { id: 5, name: "Kebutuhan Rumah", description: "Sabun, deterjen, sampo" },
];

export const suppliers: Supplier[] = [
    {
        id: 1,
        name: "Toko Grosir Makmur",
        phone: "0812-3456-7890",
        address: "Pasar Induk Kramat Jati, Jakarta",
    },
    {
        id: 2,
        name: "PT Distribusi Madura",
        phone: "0813-9876-5432",
        address: "Bangkalan, Madura",
    },
    {
        id: 3,
        name: "CV Sumber Rezeki",
        phone: "0857-1122-3344",
        address: "Surabaya, Jawa Timur",
    },
];

export const products: Product[] = [
    {
        id: 1,
        sku: "MNM-AQUA-600",
        name: "Aqua 600ml",
        categoryId: 1,
        categoryName: "Minuman",
        purchasePrice: 2500,
        sellingPrice: 4000,
        unit: "botol",
        currentStock: 48,
        minStock: 12,
    },
    {
        id: 2,
        sku: "MNM-TEH-PUC",
        name: "Teh Pucuk Harum 350ml",
        categoryId: 1,
        categoryName: "Minuman",
        purchasePrice: 3500,
        sellingPrice: 5000,
        unit: "botol",
        currentStock: 8,
        minStock: 12,
    },
    {
        id: 3,
        sku: "MNM-KOP-KAPAL",
        name: "Kopi Kapal Api Sachet",
        categoryId: 1,
        categoryName: "Minuman",
        purchasePrice: 1200,
        sellingPrice: 2000,
        unit: "sachet",
        currentStock: 120,
        minStock: 30,
    },
    {
        id: 4,
        sku: "MR-CHITATO",
        name: "Chitato Sapi Panggang 68g",
        categoryId: 2,
        categoryName: "Makanan Ringan",
        purchasePrice: 8000,
        sellingPrice: 11000,
        unit: "pcs",
        currentStock: 22,
        minStock: 10,
    },
    {
        id: 5,
        sku: "MR-OREO",
        name: "Oreo Original 137g",
        categoryId: 2,
        categoryName: "Makanan Ringan",
        purchasePrice: 7500,
        sellingPrice: 10500,
        unit: "pcs",
        currentStock: 4,
        minStock: 8,
    },
    {
        id: 6,
        sku: "RKK-SMP-MILD",
        name: "Sampoerna Mild 16",
        categoryId: 3,
        categoryName: "Rokok",
        purchasePrice: 28000,
        sellingPrice: 32000,
        unit: "bks",
        currentStock: 35,
        minStock: 20,
    },
    {
        id: 7,
        sku: "RKK-DJI-SMR",
        name: "Djarum Super 12",
        categoryId: 3,
        categoryName: "Rokok",
        purchasePrice: 24000,
        sellingPrice: 28000,
        unit: "bks",
        currentStock: 14,
        minStock: 15,
    },
    {
        id: 8,
        sku: "SMB-BERAS-5KG",
        name: "Beras Premium 5kg",
        categoryId: 4,
        categoryName: "Sembako",
        purchasePrice: 65000,
        sellingPrice: 75000,
        unit: "sak",
        currentStock: 18,
        minStock: 5,
    },
    {
        id: 9,
        sku: "SMB-MIGOR-1L",
        name: "Minyak Goreng 1L",
        categoryId: 4,
        categoryName: "Sembako",
        purchasePrice: 16000,
        sellingPrice: 19000,
        unit: "btl",
        currentStock: 6,
        minStock: 10,
    },
    {
        id: 10,
        sku: "RT-SBN-LIFEBUOY",
        name: "Sabun Lifebuoy 75g",
        categoryId: 5,
        categoryName: "Kebutuhan Rumah",
        purchasePrice: 3800,
        sellingPrice: 5500,
        unit: "pcs",
        currentStock: 26,
        minStock: 12,
    },
    {
        id: 11,
        sku: "RT-DETJN",
        name: "Detergen Sachet Rinso",
        categoryId: 5,
        categoryName: "Kebutuhan Rumah",
        purchasePrice: 1500,
        sellingPrice: 2500,
        unit: "sachet",
        currentStock: 60,
        minStock: 25,
    },
    {
        id: 12,
        sku: "MNM-SPRT-390",
        name: "Sprite 390ml",
        categoryId: 1,
        categoryName: "Minuman",
        purchasePrice: 5000,
        sellingPrice: 7000,
        unit: "btl",
        currentStock: 0,
        minStock: 6,
    },
];

export const users: AppUser[] = [
    {
        id: "u-owner-1",
        name: "Pak Imam",
        email: "owner@warungmadura.id",
        role: "owner",
        isActive: true,
        createdAt: "2025-01-12T08:00:00.000Z",
    },
    {
        id: "u-cashier-1",
        name: "Siti Aisyah",
        email: "siti@warungmadura.id",
        role: "cashier",
        isActive: true,
        createdAt: "2025-02-03T09:30:00.000Z",
    },
    {
        id: "u-cashier-2",
        name: "Budi Santoso",
        email: "budi@warungmadura.id",
        role: "cashier",
        isActive: true,
        createdAt: "2025-03-21T10:15:00.000Z",
    },
    {
        id: "u-cashier-3",
        name: "Riska Putri",
        email: "riska@warungmadura.id",
        role: "cashier",
        isActive: false,
        createdAt: "2024-11-09T14:00:00.000Z",
    },
];

function isoDaysAgo(daysAgo: number, hour = 10, minute = 0): string {
    const d = new Date();
    d.setDate(d.getDate() - daysAgo);
    d.setHours(hour, minute, 0, 0);
    return d.toISOString();
}

export const transactions: Transaction[] = [
    {
        id: "trx-0001",
        cashierId: "u-cashier-1",
        cashierName: "Siti Aisyah",
        items: [
            {
                productId: 1,
                productName: "Aqua 600ml",
                sku: "MNM-AQUA-600",
                quantity: 2,
                unitPrice: 4000,
                unitCost: 2500,
                subtotal: 8000,
            },
            {
                productId: 4,
                productName: "Chitato Sapi Panggang 68g",
                sku: "MR-CHITATO",
                quantity: 1,
                unitPrice: 11000,
                unitCost: 8000,
                subtotal: 11000,
            },
        ],
        totalAmount: 19000,
        totalCost: 13000,
        paymentMethod: "cash",
        status: "completed",
        createdAt: isoDaysAgo(0, 9, 12),
    },
    {
        id: "trx-0002",
        cashierId: "u-cashier-1",
        cashierName: "Siti Aisyah",
        items: [
            {
                productId: 6,
                productName: "Sampoerna Mild 16",
                sku: "RKK-SMP-MILD",
                quantity: 1,
                unitPrice: 32000,
                unitCost: 28000,
                subtotal: 32000,
            },
        ],
        totalAmount: 32000,
        totalCost: 28000,
        paymentMethod: "qris",
        status: "completed",
        createdAt: isoDaysAgo(0, 11, 5),
    },
    {
        id: "trx-0003",
        cashierId: "u-cashier-2",
        cashierName: "Budi Santoso",
        items: [
            {
                productId: 8,
                productName: "Beras Premium 5kg",
                sku: "SMB-BERAS-5KG",
                quantity: 1,
                unitPrice: 75000,
                unitCost: 65000,
                subtotal: 75000,
            },
            {
                productId: 9,
                productName: "Minyak Goreng 1L",
                sku: "SMB-MIGOR-1L",
                quantity: 2,
                unitPrice: 19000,
                unitCost: 16000,
                subtotal: 38000,
            },
        ],
        totalAmount: 113000,
        totalCost: 97000,
        paymentMethod: "transfer",
        status: "completed",
        createdAt: isoDaysAgo(1, 14, 20),
    },
    {
        id: "trx-0004",
        cashierId: "u-cashier-1",
        cashierName: "Siti Aisyah",
        items: [
            {
                productId: 3,
                productName: "Kopi Kapal Api Sachet",
                sku: "MNM-KOP-KAPAL",
                quantity: 5,
                unitPrice: 2000,
                unitCost: 1200,
                subtotal: 10000,
            },
        ],
        totalAmount: 10000,
        totalCost: 6000,
        paymentMethod: "cash",
        status: "completed",
        createdAt: isoDaysAgo(2, 8, 30),
    },
    {
        id: "trx-0005",
        cashierId: "u-cashier-2",
        cashierName: "Budi Santoso",
        items: [
            {
                productId: 11,
                productName: "Detergen Sachet Rinso",
                sku: "RT-DETJN",
                quantity: 4,
                unitPrice: 2500,
                unitCost: 1500,
                subtotal: 10000,
            },
            {
                productId: 10,
                productName: "Sabun Lifebuoy 75g",
                sku: "RT-SBN-LIFEBUOY",
                quantity: 2,
                unitPrice: 5500,
                unitCost: 3800,
                subtotal: 11000,
            },
        ],
        totalAmount: 21000,
        totalCost: 13600,
        paymentMethod: "cash",
        status: "completed",
        createdAt: isoDaysAgo(3, 16, 45),
    },
    {
        id: "trx-0006",
        cashierId: "u-cashier-1",
        cashierName: "Siti Aisyah",
        items: [
            {
                productId: 7,
                productName: "Djarum Super 12",
                sku: "RKK-DJI-SMR",
                quantity: 2,
                unitPrice: 28000,
                unitCost: 24000,
                subtotal: 56000,
            },
        ],
        totalAmount: 56000,
        totalCost: 48000,
        paymentMethod: "qris",
        status: "completed",
        createdAt: isoDaysAgo(4, 19, 0),
    },
    {
        id: "trx-0007",
        cashierId: "u-cashier-2",
        cashierName: "Budi Santoso",
        items: [
            {
                productId: 2,
                productName: "Teh Pucuk Harum 350ml",
                sku: "MNM-TEH-PUC",
                quantity: 3,
                unitPrice: 5000,
                unitCost: 3500,
                subtotal: 15000,
            },
            {
                productId: 5,
                productName: "Oreo Original 137g",
                sku: "MR-OREO",
                quantity: 1,
                unitPrice: 10500,
                unitCost: 7500,
                subtotal: 10500,
            },
        ],
        totalAmount: 25500,
        totalCost: 18000,
        paymentMethod: "cash",
        status: "completed",
        createdAt: isoDaysAgo(5, 12, 15),
    },
    {
        id: "trx-0008",
        cashierId: "u-cashier-1",
        cashierName: "Siti Aisyah",
        items: [
            {
                productId: 1,
                productName: "Aqua 600ml",
                sku: "MNM-AQUA-600",
                quantity: 6,
                unitPrice: 4000,
                unitCost: 2500,
                subtotal: 24000,
            },
        ],
        totalAmount: 24000,
        totalCost: 15000,
        paymentMethod: "cash",
        status: "completed",
        createdAt: isoDaysAgo(6, 10, 0),
    },
];

export const stockIns: StockIn[] = [
    {
        id: "in-0001",
        userId: "u-owner-1",
        userName: "Pak Imam",
        supplierId: 1,
        supplierName: "Toko Grosir Makmur",
        items: [
            {
                productId: 1,
                productName: "Aqua 600ml",
                quantity: 48,
                unitCost: 2500,
            },
            {
                productId: 2,
                productName: "Teh Pucuk Harum 350ml",
                quantity: 24,
                unitCost: 3500,
            },
        ],
        totalCost: 48 * 2500 + 24 * 3500,
        receivedDate: isoDaysAgo(2, 8).slice(0, 10),
        notes: "Restock minggu kedua",
        createdAt: isoDaysAgo(2, 8),
    },
    {
        id: "in-0002",
        userId: "u-cashier-2",
        userName: "Budi Santoso",
        supplierId: 2,
        supplierName: "PT Distribusi Madura",
        items: [
            {
                productId: 6,
                productName: "Sampoerna Mild 16",
                quantity: 20,
                unitCost: 28000,
            },
            {
                productId: 7,
                productName: "Djarum Super 12",
                quantity: 20,
                unitCost: 24000,
            },
        ],
        totalCost: 20 * 28000 + 20 * 24000,
        receivedDate: isoDaysAgo(5, 9).slice(0, 10),
        notes: "Pengiriman bulanan",
        createdAt: isoDaysAgo(5, 9),
    },
];
